### ISSUE TITLE
Sign Out Problem

### ISSUE THREAD

**Issue by barriault** [joshsoftware/sso-devise-omniauth-client#1]
Thanks Josh for all the hard work. You saved me a bunch of time trying to figure this all out on my own. There is one quirk that remains to be solved. When you sign out of one child app you remained signed in on the other child apps. I'm guessing this is because even though you destroy the session of the child app and the auth app, the remaining child apps still have their session. I'm not sure how to solve this. Any ideas?

**Comment by barriault** [comment]
Hey Josh, I actually figured out how to get this to work. You need to use the same secret_token (config/initializers/secret_token.rb) and the same session store key (config/initializers/session_store.rb) across all the apps.

Then in your config/environments you need to set the session domain. For production.rb use:
    config.action_controller.session = { :domain => ".mydomain.com" }
And for development.rb use:
    config.action_controller.session = { :domain => ".rails.localhost" }
This allows all the apps to share the same cookie. Sweet!

**Comment by gautamrege** [comment]
Hey ! Awesome find - I hacked my way around this earlier with a custom /sign_out on the client app redirecting to the provider to '/sign_out'. (yuck!)

This is SWEEET!

**Comment by barriault** [comment]
I noticed in the passenger log when the app started that the config methods above are deprecated. So I moved the code to the config/initializers/session_store.rb file and it looks like this:

```
 if ENV['RAILS_ENV'] == 'production'
   Home::Application.config.session_store :cookie_store, :key => '_myapp_session', :domain => '.mydomain.com'
 else
   Home::Application.config.session_store :cookie_store, :key => '_myapp_session', :domain => '.rails.localhost'
 end
```

Oh, and I had to add an entry to my hosts file for rails.localhost. Anyway, just thought I'd pass it on.

**Comment by gautamrege** [comment]
Thanks! I'll get the changes made to the repo asap.
