### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pjmorse** [joshsoftware/sso-devise-omniauth-client#6]
We'd like to use this gem and [its provider sister](/joshsoftware/sso-devise-omniauth-provider) in a project under development, but we need to make sure it uses a compatible license (in our case, [Simplified BSD](http://www.opensource.org/licenses/BSD-2-Clause), [MIT](http://www.opensource.org/licenses/MIT), or [Apache 2.0](http://www.opensource.org/licenses/Apache-2.0)). There is no license specified for this project; does it have one? If not, can it be released under one of these three?

**Comment by gautamrege** [comment]
Added the MIT license

**Comment by pjmorse** [comment]
Thank you!
