### ISSUE TITLE
Clarification on included lib/josh_id.rb strategy

### ISSUE THREAD

**Issue by abitdodgy** [joshsoftware/sso-devise-omniauth-client#7]
Just to clarify, am I right in thinking that the included strategy `lib/josh_id.rb` is not used directly in this app? This app is just a consumer. The provider app is the one that needs to implement the strategy, right?

So including it here is just for what, convenience?

**Comment by gautamrege** [comment]
Yes. It is used. 

The Omniauth config uses it and calls the Provider. This is the client side code to get the access token.

**Comment by abitdodgy** [comment]
Yes of course. This would be the equivalent of the gem added to the client app. Like omniauth-facebook, for example.
